### ISSUE TITLE
README.md for debian packaging

### ISSUE THREAD

**Issue by hcwinsemius** [OpenDroneMap/odm360#109]

**Comment by ivangayton** [comment]
Stubs included. I'd originally intended to create one in the ```debian``` directory and another in the ```.github``` directory. However, it turns out that anything in the ```.github``` directory hijacks the main README in the root directory on the GitHub website (apparently if there's a README.md in the ```.github``` directory that's what is displayed on the main page of the repo).

So I'll put it all in the ```debian``` directory, and add some links in the main README to point to it.
