### ISSUE TITLE
support PiCamera objects (side-by-side with gphoto2 Camera objects)

### ISSUE THREAD

**Issue by hcwinsemius** [OpenDroneMap/odm360#13]
For the raspi cameras, we'll need to either supplement or prepare a similarly functioning class for PiCamera objects see [https://projects.raspberrypi.org/en/projects/getting-started-with-picamera](https://projects.raspberrypi.org/en/projects/getting-started-with-picamera)

**Comment by smathermather** [comment]
Yes, and it looks like it uses a dedicated port, so we will likely need more hardware, ala:
* https://www.timpoulsen.com/2018/multiple-cameras-with-a-single-raspberry-pi.html
* https://www.arducam.com/docs/cameras-for-raspberry-pi/multi-camera-adapter-board/introduction/

We might need more than one PI to get up to 5 or 7 cameras.

**Comment by smathermather** [comment]
But maybe if we do pi zeros for control and transfer, it won't be too much of an investment. It's not clear that the above links allow the new high quality pi cam.

**Comment by smathermather** [comment]
Interesting alternative exist that are slightly more turnkey: https://www.arducam.com/product/b0243-arducam-imx477-hq-camera-6/

**Comment by smathermather** [comment]
Plus boards meant for 360:
https://www.robotshop.com/en/arducam-arduino-panorama-360-shield.html

**Comment by smathermather** [comment]
Adding these here for posterity:
https://www.arducam.com/raspberry-pi-high-quality-hq-camera-imx477/

**Comment by smathermather** [comment]
Via @ivangayton for camera synchronization testing: https://www.instructables.com/id/High-speed-Clock-for-Slow-motion-Videos/

**Comment by smathermather** [comment]
Adding this here instead of in a readme:

# Exploring the options for a Raspberry PI alternative setup

The existing ODM 360 leverages the Sony α6000 and gphoto2 for control. This has advantages: the primary being that the α6000 is a very nice camera with excellent available optics, a physical leaf style shutter (ideal for photogrammetry), and a great chipset. The disadvantages are cost, weight, and freedom. By freedom we mean that the camera itself is not free or open source.

![](https://www.raspberrypi.org/homepage-9df4b/static/f71633ede5f3881b071d5c7539a5b1f4/f8408/03b5b033-5aca-40a7-ae4a-1592a9403890_CAM%2BHERO%2BALT%2B2.jpg)

Using the [Raspberry Pi High Quality Camera](https://www.raspberrypi.org/products/raspberry-pi-high-quality-camera/) may be an affordable alternative that could give good results and be free and open source in it's full implementation, and fully supported until 2027. The chipset and optics are likely to be quite adequate for most purposes, so let's step through the logistics and cost. One caveat is that the Pi High Quality camera is built around a video camera chip, and has an electronic, not physical shutter. This has some real implications for photogrammetry which we won't address here.

* $50 camera
* 7.564 (H) x 5.476 (V) mm
* $25, 6mm lens

Using a [field of view calculator](https://zwww.scantips.com/lights/fieldofview.html), this gives us 49.06° vertical field of view, 64.38° horizontal. To create a 360° array, we would need 6 (H) or 7 (V) cameras mounted, which would total $450-$525, which is approximately the price of a single Sony α6000 without the separate lens the Sony needs. These costs do not yet include the cost of the controlling Raspberry Pi nor GPS.

The Sony α6000 rig is 24.3MP x 5 cameras yield a ~120MP synthetic image. The proposed Raspberry PI High Quality Camera is 12.3MP x 7 cameras yielding ~85MP. For comparison, a GoPro Max is 16.6MP.

**Comment by smathermather** [comment]
Added a couple commits to add a Pi camera control:
https://github.com/OpenDroneMap/odm360/commit/f32035d36cae45c60ceb4fce3bf55dc34930026a
https://github.com/OpenDroneMap/odm360/commit/8b2c3dc45e745c31ae123811f38bdee81dfd2f88
